<a href="https://colab.research.google.com/github/mayurmore258/Python-Bootcamp-Exercises/blob/main/Numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math

In [2]:
arr = np.array([1,2,3])
print(arr)

arr0 = np.zeros((2,2))
print("\n",arr0)

arr1 = np.ones((2,4))
print("\n",arr1)

arrRand = np.random.random((3, 4))
print("\n",arrRand)

arrEmpty = np.empty((3,4))
print("\n", arrEmpty)

arrArange = np.arange(1,10,2)
print("\n", arrArange)

arrLinespace = np.linspace(3,9,10)
print("\n", arrLinespace)

[1 2 3]

 [[0. 0.]
 [0. 0.]]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 [[0.21790127 0.54312305 0.8717854  0.02803694]
 [0.56286777 0.52769235 0.62060026 0.63824606]
 [0.49315642 0.32451248 0.73180582 0.60775161]]

 [[0.21790127 0.54312305 0.8717854  0.02803694]
 [0.56286777 0.52769235 0.62060026 0.63824606]
 [0.49315642 0.32451248 0.73180582 0.60775161]]

 [1 3 5 7 9]

 [3.         3.66666667 4.33333333 5.         5.66666667 6.33333333
 7.         7.66666667 8.33333333 9.        ]


#Array attributes

In [3]:
arr= np.array([[[1,2,3],[1,4,2],[3,4,3]],
              [[5,12,3],[34,54,23],[1,6,4]]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr[1, 1, 0])

(2, 3, 3)
3
18
int64
34


#Slicing

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
#Syntax : arr[start:stop:step]
print(arr[1:10:3])
print(arr[0:4])
print(arr[::-1])  #to print in reverse order
print(arr[-1:-6:-1]) #reverse slicing

#slicing in 2D array
arr2 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9],
                [10,11,12]])
print(arr2[1:3,1:3])

[2 5 8]
[1 2 3 4]
[10  9  8  7  6  5  4  3  2  1]
[10  9  8  7  6]
[[5 6]
 [8 9]]


#Adding, removing, and sorting elements

In [25]:
a = np.array([3,4,5,2,1])
b = np.array([8,6,2,6,3])

sorted = np.sort(a)
print(sorted)

arg_sort = np.argsort(a)
print(arg_sort)
print()

concatenated = np.concatenate((a, b))
print(concatenated)



[1 2 3 4 5]
[4 3 0 1 2]

[3 4 5 2 1 8 6 2 6 3]


#Sorting n dimension array

In [72]:
arr = np.array([[[12, 3],
                 [4, 11]],

                [[7, 9],
                 [5, 8]],

                [[10, 8],
                 [6, 1]]])

a = arr.reshape(4,3)
print(a)

row_sort = np.sort(a)
print(row_sort)

column_sort = np.sort(a, axis = 0)
print("\n", column_sort)

print()
print()

arr_row_sort = np.sort(arr)
print(arr_row_sort)

b = arr.reshape(2,2,3,1)
print(np.ndim(b))

[[12  3  4]
 [11  7  9]
 [ 5  8 10]
 [ 8  6  1]]
[[ 3  4 12]
 [ 7  9 11]
 [ 5  8 10]
 [ 1  6  8]]

 [[ 5  3  1]
 [ 8  6  4]
 [11  7  9]
 [12  8 10]]


[[[ 3 12]
  [ 4 11]]

 [[ 7  9]
  [ 5  8]]

 [[ 8 10]
  [ 1  6]]]
4


#Accessing array elements

In [71]:
arr = np.array([[[12, 3],
                 [4, 11]],

                [[7, 9],
                 [5, 8]],

                [[10, 8],
                 [6, 1]]])

print(np.shape(arr))
print(arr[2,0,1])
print(arr[1,1,1])
print(arr[:,:,1])



(3, 2, 2)
8
8
[[ 3 11]
 [ 9  8]
 [ 8  1]]


#Arithmetic operations on arrays

In [6]:
'''
Addition(+)
Subtrction(-)
Division(/)
Multiplication(*)
Matrix multiplication(@)
Floor Division(//)
Exponentiation(**)
Modulo(%)
Transpose(.transpose()) this is a function
'''

a = np.array([[1,2],
              [3,4]])
b = np.array([[10,20],
              [30,40]])

print("\n", a+b)
print("\n", a-b)
print("\n", a*b)
print("\n", a/b)
print("\n", a//b)
print("\n", a**b)
print("\n", a@b)
print("\n", a%b)
print(a.transpose())


 [[11 22]
 [33 44]]

 [[ -9 -18]
 [-27 -36]]

 [[ 10  40]
 [ 90 160]]

 [[0.1 0.1]
 [0.1 0.1]]

 [[0 0]
 [0 0]]

 [[              1         1048576]
 [205891132094649               0]]

 [[ 70 100]
 [150 220]]

 [[1 2]
 [3 4]]
[[1 3]
 [2 4]]


#Reshaping and flattening of arrays

In [20]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a = arr.flatten()
a[0] =25
print(a)
print(arr)

brr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b = brr.flatten()
print(b)

reshaped_a = arr.reshape((4,3))
print(reshaped_a)

[25  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 2 3 4 5 6 7 8]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
#ravel() function
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr1 = arr.ravel()
arr1[0] = 25
print(arr)
print(arr1)

[[25  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[25  2  3  4  5  6  7  8  9 10 11 12]


#Reverse an array

In [24]:
arr = np.array([32,45,2,3,34,2,3,723,8,54,67,23])
sorted_arr = np.flip(arr)
print(sorted_arr)

[ 23  67  54   8 723   3   2  34   3   2  45  32]
